[ 2024-12-08 22:59:24,596 ] werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.93.153:8080
[ 2024-12-08 22:59:24,598 ] werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2024-12-08 22:59:28,600 ] werkzeug - INFO - 127.0.0.1 - - [08/Dec/2024 22:59:28] "GET / HTTP/1.1" 200 -
[ 2024-12-08 22:59:29,302 ] werkzeug - INFO - 127.0.0.1 - - [08/Dec/2024 22:59:29] "GET / HTTP/1.1" 200 -
[ 2024-12-08 22:59:30,267 ] werkzeug - INFO - 127.0.0.1 - - [08/Dec/2024 22:59:30] "GET / HTTP/1.1" 200 -
[ 2024-12-08 22:59:33,186 ] root - INFO - Updated DATA_DOWNLOAD_URL to: https://drive.google.com/file/d/1ECfl3dtYyfivY8kYPq7RHUB-2vf61/view?usp=share_link
[ 2024-12-08 22:59:33,187 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2024-12-08 22:59:33,187 ] root - INFO - Getting the data from URL
[ 2024-12-08 22:59:33,187 ] root - INFO - Entered initiate_data_ingestion method of Data_Ingestion class
[ 2024-12-08 22:59:33,189 ] root - INFO - Downloading data from  into file artifacts\data_ingestion\data.zip
[ 2024-12-08 22:59:33,190 ] root - ERROR - Error during training: Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\pipeline\training_pipeline.py] line number [98] error message [Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\pipeline\training_pipeline.py] line number [37] error message [Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\components\data_ingestion.py] line number [71] error message [Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\components\data_ingestion.py] line number [34] error message [list index out of range]]]]
[ 2024-12-08 22:59:33,191 ] werkzeug - INFO - 127.0.0.1 - - [08/Dec/2024 22:59:33] "[35m[1mPOST /train HTTP/1.1[0m" 500 -
[ 2024-12-08 22:59:37,721 ] root - INFO - Updated DATA_DOWNLOAD_URL to: https://drive.google.com/file/d/1ECfl3dtYyfivY8kYPq7RHUB-2vf61/view?usp=share_link
[ 2024-12-08 22:59:37,721 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2024-12-08 22:59:37,721 ] root - INFO - Getting the data from URL
[ 2024-12-08 22:59:37,721 ] root - INFO - Entered initiate_data_ingestion method of Data_Ingestion class
[ 2024-12-08 22:59:37,723 ] root - INFO - Downloading data from  into file artifacts\data_ingestion\data.zip
[ 2024-12-08 22:59:37,724 ] root - ERROR - Error during training: Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\pipeline\training_pipeline.py] line number [98] error message [Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\pipeline\training_pipeline.py] line number [37] error message [Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\components\data_ingestion.py] line number [71] error message [Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\components\data_ingestion.py] line number [34] error message [list index out of range]]]]
[ 2024-12-08 22:59:37,725 ] werkzeug - INFO - 127.0.0.1 - - [08/Dec/2024 22:59:37] "[35m[1mPOST /train HTTP/1.1[0m" 500 -
[ 2024-12-08 22:59:48,056 ] root - INFO - Updated DATA_DOWNLOAD_URL to: https://drive.google.com/file/d/1ECfl3dtYyfivY8kYPq7RHUB-2vf61/view?usp=share_link
[ 2024-12-08 22:59:48,056 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2024-12-08 22:59:48,056 ] root - INFO - Getting the data from URL
[ 2024-12-08 22:59:48,057 ] root - INFO - Entered initiate_data_ingestion method of Data_Ingestion class
[ 2024-12-08 22:59:48,057 ] root - INFO - Downloading data from  into file artifacts\data_ingestion\data.zip
[ 2024-12-08 22:59:48,058 ] root - ERROR - Error during training: Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\pipeline\training_pipeline.py] line number [98] error message [Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\pipeline\training_pipeline.py] line number [37] error message [Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\components\data_ingestion.py] line number [71] error message [Error occurred python script name [E:\New\main_yolo_v5\End-to-end-Waste-Detection-Using-Yolo-v5-main\wasteDetection\components\data_ingestion.py] line number [34] error message [list index out of range]]]]
[ 2024-12-08 22:59:48,058 ] werkzeug - INFO - 127.0.0.1 - - [08/Dec/2024 22:59:48] "[35m[1mPOST /train HTTP/1.1[0m" 500 -
[ 2024-12-08 23:00:02,292 ] werkzeug - INFO - 127.0.0.1 - - [08/Dec/2024 23:00:02] "GET / HTTP/1.1" 200 -
